import os
import pickle
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

def upload_to_youtube(video_path, title="فيديو جديد حياكم🔥🔥🔥", description="Generated by AI"):
    if not os.path.exists("token.pickle"):
        raise Exception("❌ token.pickle not found!")

    with open("token.pickle", "rb") as token_file:
        creds = pickle.load(token_file)

    youtube = build("youtube", "v3", credentials=creds)
    request_body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": ["AI", "shorts", "pexels", "automation"],
            "categoryId": "22"
        },
        "status": {
            "privacyStatus": "public"
        }
    }

    media = MediaFileUpload(video_path)
    request = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media
    )
    response = request.execute()
    print(f"✅ تم رفع الفيديو: https://youtu.be/{response['id']}")
